dist: trusty
sudo: false

language: scala
scala:
  - 2.12.4

jdk:
  - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
   - bash <(curl -s https://codecov.io/bash)
