addSbtPlugin("org.scoverage"      % "sbt-scoverage"         % "1.6.0-M3")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph"  % "0.9.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"           % "1.0.11")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"               % "1.1.2")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"         % "0.9.0")