addSbtCoursier
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.0.4")
addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.2.10")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"             % "1.6.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"      % "0.9.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"               % "1.0.11")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"                   % "1.1.2")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"             % "0.9.0")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"                % "4.0.0")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"              % "0.14.10")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"       % "1.4.1")
